# Generated by Django 4.2 on 2023-05-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('utype', models.CharField(max_length=20)),
            ],
        ),
    ]
