# Generated by Django 4.2 on 2023-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='username',
            field=models.TextField(default=None),
        ),
    ]
