# Generated by Django 4.2 on 2023-05-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_userinfo_password_userinfo_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.TextField()),
                ('product_name', models.TextField()),
                ('category', models.TextField()),
                ('price', models.BigIntegerField()),
                ('quantity', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('warranty', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
