# Generated by Django 4.2 on 2023-06-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_about_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdesc', models.TextField(default=None)),
                ('sdesc', models.TextField(default=None)),
                ('tname', models.TextField(default=None)),
                ('tphoto', models.ImageField(default=None, upload_to='')),
                ('services', models.TextField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
