# Generated by Django 4.2 on 2023-06-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_abouts_delete_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abouts',
            old_name='services',
            new_name='address',
        ),
        migrations.AddField(
            model_name='abouts',
            name='aproduct',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='abouts',
            name='contact',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='abouts',
            name='offer',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='abouts',
            name='price',
            field=models.TextField(default=None),
        ),
    ]
