# Generated by Django 4.2 on 2023-06-16 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_rename_services_abouts_address_abouts_aproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouts',
            name='aproduct',
        ),
    ]
