# Generated by Django 4.2 on 2023-06-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_abouts_aproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.TextField(default=None)),
                ('aproduct', models.TextField(default=None)),
                ('address', models.TextField(default=None)),
                ('price', models.TextField(default=None)),
                ('offer', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='address',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='price',
        ),
    ]
