# Generated by Django 4.2 on 2023-06-16 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_products_remove_abouts_address_remove_abouts_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Home',
        ),
    ]
