# Generated by Django 4.2 on 2023-06-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_abouts_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='hname',
            field=models.TextField(default=None),
        ),
    ]
